# Generated by Django 5.0.4 on 2024-05-04 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_meja', models.IntegerField()),
                ('kapasitas', models.IntegerField()),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Kosong', 'Kosong'), ('Dibersihkan', 'Dibersihkan')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tanggal_bergabung', models.DateField(auto_now_add=True)),
                ('poin_loyalitas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_tersedia', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], max_length=20)),
                ('metode_pembayaran', models.CharField(choices=[('Tunai', 'Tunai'), ('Debit', 'Debit'), ('Kredit', 'Kredit')], max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('meja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.meja')),
                ('pelanggan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pelanggan')),
            ],
        ),
    ]
