# Generated by Django 5.0.4 on 2024-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kategori',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='metode_pembayaran',
            field=models.CharField(choices=[('Tunai', 'Tunai'), ('Debit', 'Debit'), ('qris', 'qris')], max_length=20),
        ),
    ]
