# Generated by Django 5.0.4 on 2024-07-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_menu_kategori_alter_pesanan_metode_pembayaran'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='pelanggan',
            name='poin_loyalitas',
        ),
    ]
