# Generated by Django 5.0.4 on 2024-07-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pesanan_jumlah_pesanan_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan',
            name='total_harga',
        ),
    ]
