# Generated by Django 5.0.4 on 2024-07-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_total_harga_pesanan_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pesanan', to='api.menu'),
        ),
    ]
