# Generated by Django 5.0.4 on 2024-07-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_kategori_remove_pesanan_menu_remove_pesanan_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='kategori',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
